# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5067bf7747f50164fc3b9754eca550a211fb5ba040f0bb76aa1901bad98ff1d59193495c8c967582d8fa81ea2f41d5b15bf6f5c7082feadf04d68617241be2b9

test:
  secret_key_base: 64b03cd0fb229cd9f650ffd1d20d3ebb7e5d20b47b4e780fe60410aefdd6edc239a95d01f312974c7e3874e7d565e02d37f362fde5b8858bc38d58bc6787587b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
